### ISSUE TITLE
Modelevaluator, create 1 input for sklearn and custom metrics

### ISSUE THREAD

**Issue by BartvanWoesik** [BartvanWoesik/model-forge#8]
Currently the modelevaluator takes different inputs for sklearn and custom metrics.
It is better to except 1 input which should be:

- [ ] A dictionary
- [ ] metric name as key
- [ ] value is callable that excepts y_pred and y_true

**Comment by RJJZitman** [comment]
@BartvanWoesik PR staat klaar in home_credit
